language: php

sudo: false

matrix:
    include:
        - php: 5.3
        - php: 5.3
          env: deps=low
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7
        - php: hhvm
    fast_finish: true

before_script:
    - cp phpunit.xml.dist phpunit.xml
    - composer update
    - mkdir -p log/codeCoverage

script: phpunit

notifications:
  email:
    -  kapil@kapilsharma.info

addons:
    code_climate:
        repo_token: a57d93296df9c8663e493a6158ab1e0c16f3eaf458b2396d221e0224bd863492
