language: php

sudo: false

matrix:
    include:
        - php: 5.3.3
        - php: 5.3
        - php: 5.3
          env: deps=low
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7
        - php: hhvm
    fast_finish: true

before_script:
    - cp phpunit.xml.dist phpunit.xml
    - composer install

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email:
    -  kapil@kapilsharma.info